CREATE TABLE public.category (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NOT NULL,
	description varchar NOT NULL,
	CONSTRAINT category_id PRIMARY KEY (id),
	CONSTRAINT category_name UNIQUE (name)
);