-- public."location" definição

-- Drop table

-- DROP TABLE public."location";

CREATE TABLE public."location" (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"zone" int4 NOT NULL,
	is_locked bool NOT NULL,
	indentification varchar NOT NULL,
	aisle varchar NULL,
	"column" varchar NULL,
	"level" varchar NULL,
	slot varchar NULL,
	"depth" varchar NULL,
	CONSTRAINT location_id PRIMARY KEY (id),
	CONSTRAINT location_unique UNIQUE (indentification)
);