CREATE TABLE public.person (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar NOT NULL,
	"document" varchar NOT NULL,
	address varchar NOT NULL,
	CONSTRAINT person_document UNIQUE (document),
	CONSTRAINT person_id PRIMARY KEY (id)
);